trigger: none

pool: Default

resources:
  pipelines:
    - pipeline: source
      source: merge
      trigger:
        branches:
          - master
          
stages:
  - stage: Deploy
    jobs:
    - deployment: DeployApplication
      displayName: "Deploying Application on Develop"
      environment: 'develop'
      variables:
        environment: 'develop'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: templates/deploy.yml
