steps:
  - trigger: "nodeexpresstemplate-quality"
    label: ":mag_right:"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
  - wait
  - label: ":docker: Building"
    command:
      - .buildkite/scripts/docker-build.sh
    env:
       APPLICATION: "hello-nodejs"
