env:
  DOCKER_IMAGE_KEY: "docker-image-key"

steps:
  - input: "Release Informations"
    fields:
      - text: "Which Docker Image Version should deploy ?"
        key: "${DOCKER_IMAGE_KEY}"
    if: "build.env('DOCKER_IMAGE') == null"

  - wait

  - command: ".buildkite/scripts/release.sh"
    env:
      DOCKER_IMAGE: "${DOCKER_IMAGE}"
      DOCKER_IMAGE_KEY: "${DOCKER_IMAGE_KEY}"
