steps:
  - input: "Release Informations"
    fields:
      - text: "Which Docker Image Version should deploy ?"
        key: "docker-image"
    if: "build.env('DOCKER_IMAGE') == null"

  - wait

  - command: "ok should go! ${DOCKER_IMAGE}"
