env:
  APPLICATION: "hello-nodejs"
  DOCKER_IMAGE: "${dockeruser}/${APPLICATION}:${BUILDKITE_BUILD_ID}"

steps:
  - trigger: "nodeexpresstemplate-quality"
    label: ":mag_right:"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
  - wait
  - label: ":docker: Building"
    command:
      - .buildkite/scripts/docker-build.sh
    env:
       DOCKER_IMAGE: "${DOCKER_IMAGE}"
  - wait
  - trigger: "nodeexpresstemplate-release-dev"
    label: ":rocket: releasing dev"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
        DOCKER_IMAGE: "${DOCKER_IMAGE}" 
