steps:
  - label: ":npm: installing dependencies"
    command:
      - npm install
      - ls -al
      - echo "---------"
      - ls -al ./node_modules
    artifact_paths:
      - "./node_modules/"
  
  - wait

  - label: ":eslint: linting"
    command:
      - mkdir -p node_modules
      - buildkite-agent artifact download "./node_modules/*" "node_modules" 
      - npm run lint

  - label: ":test_tube: testing"
    command:
      - mkdir -p node_modules
      - buildkite-agent artifact download "./node_modules/*" "node_modules" 
      - npm run test